# Generated by Django 4.1.3 on 2023-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('degree', models.CharField(max_length=100, verbose_name='Научная степень')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('keywords', models.TextField(verbose_name='Ключевые слова')),
                ('research_topics', models.TextField(verbose_name='Темы научных работ')),
                ('competitions_participation', models.TextField(verbose_name='Участие в конкурсах')),
                ('conferences', models.TextField(verbose_name='Конференции')),
                ('research_activities', models.TextField(verbose_name='Научные исследования')),
            ],
            options={
                'verbose_name': 'Научный работник',
                'verbose_name_plural': 'Научные работники',
            },
        ),
    ]
