# Generated by Django 4.1.3 on 2023-09-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.TextField(blank=True, verbose_name='Конференции')),
                ('country', models.TextField(blank=True, verbose_name='')),
                ('city', models.TextField(blank=True, verbose_name='')),
                ('year', models.IntegerField(blank=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='image')),
                ('research_activities_website', models.URLField(verbose_name='Научные исследования')),
            ],
            options={
                'verbose_name': 'Научный исследованиe',
                'verbose_name_plural': 'Научные исследования',
            },
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='competitions_participation',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='research_activities',
        ),
        migrations.AddField(
            model_name='scientist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='conferences',
        ),
        migrations.AlterField(
            model_name='scientist',
            name='specialization',
            field=models.TextField(verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='research_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.research'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='conferences',
            field=models.ManyToManyField(to='main_app.conference'),
        ),
    ]
