# Generated by Django 4.1.3 on 2023-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_conference_research_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.TextField(blank=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='country',
            field=models.TextField(blank=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
    ]
