# Generated by Django 4.1.3 on 2023-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_conference_city_alter_conference_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientist',
            name='research_link',
        ),
        migrations.AddField(
            model_name='scientist',
            name='research_link',
            field=models.ManyToManyField(to='main_app.research'),
        ),
    ]
